### ISSUE TITLE
Separators look wrong

### ISSUE THREAD

**Issue by joncol** [domtronn/spaceline-all-the-icons.el#11]
Hi (again!) :)

When using certain themes, the separators look wrong:

![image](https://cloud.githubusercontent.com/assets/194062/25127598/be9c14a2-2436-11e7-8e0e-07be7469320e.png)

This example uses `gotham-theme`.

I don't know if this is a powerline issue, a spaceline issue or a spaceline-all-the-icons issue. Maybe you do?

**Comment by joncol** [comment]
I just noticed that this glitch apparently goes away when splitting the Emacs window so that there are two windows side by side:

![selection_012](https://cloud.githubusercontent.com/assets/194062/25128851/a9023efa-243b-11e7-93d6-3e7f260ec2e3.png)

Very strange...

**Comment by joncol** [comment]
Ah.. Changing `spaceline-all-the-icons-separator-type` to `arrow` or any of the other types, makes this go away. That's good enough for me.

I'll leave this open so that you can check if you can reproduce this using the `slant` separator type, if and when you have time.

**Comment by domtronn** [comment]
That is strange that it goes away...

I'm kind of aware this though, the way the separators work is they're actually a unicode character, so I colour them with a foreground & background like all other text - The problem is when you're transitioning from a dark background to a light background, the character has the dark colour as the _foreground_ and the light colour as the _background_ and since Emacs doesn't aline characters to the bottom, you _can_ end up with a tiny gap 😅 

And technically this will be happening for the `arrow` type, but since it doesn't have a hard line at the bottom you won't see it.

This can also change based on the fonts used and things... I've been thinking of a better solution to this and have a couple of ideas but they're all kind of difficult, so was hoping it wouldn't be too much of an issue for people!
