### ISSUE TITLE
Styling only inactive windows

### ISSUE THREAD

**Issue by mfiano** [domtronn/spaceline-all-the-icons.el#2]
The included theme is only applying a style to all inactive window modelines. Active window is completely blank.

**Comment by domtronn** [comment]
Could you please update the package and try again?

The reason it's blank is because one of the spaceline segments is throwing an error... Unfortunately, it's not easy to get output in order to debug this.

If you could have a look inside your `*Messages*` buffer and paste the output here, that would be useful.

Alternatively, you can toggle off each of the `spaceline-all-the-icons` segments one at a time until the mode line shows up - This will indicate which segment has the error in.

**Comment by mfiano** [comment]
Sure, the messages buffer shows:

```
Loading /home/axion/.emacs.d/config.el (source)...
Loading /home/axion/.emacs.d/custom.el (source)...done
Updating /home/axion/.emacs.d/quelpa/melpa
Loading /home/axion/.emacs.d/etc/recent...done
Turn on counsel-projectile key bindings
Loading /home/axion/.emacs.d/config.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a.
Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (wrong-type-argument number-or-marker-p nil) [16 times]
<left-fringe> <drag-mouse-1> is undefined
Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (wrong-type-argument number-or-marker-p nil) [47 times]
```

and here is what I see:
![example](https://img.axity.net/img-20170410053900.png)

**Comment by mfiano** [comment]
@domtronn This error seems to lie in the symbol `all-the-icons-package-updates`

**Comment by domtronn** [comment]
Thanks for debugging that!
I've just pushed a fix, if you do a pull let me know if this fixes it 😃 

In the mean time, I'm going to try and write a debug function which toggles segments on and off waiting for an error and then tells you what segment failed... I feel that would be useful.

**Comment by mfiano** [comment]
Thanks. By the way, I'm trying to figure out how the faces are defined. I'd like the active ml face to be nearly the same color as the inactive. Also I can't figure out where the items for each are defined...I also want the exact same segments for active and inactive.

**Comment by domtronn** [comment]
The faces are defined as 

* `spaceline-highlight-face` _(This is the bright coloured face)_
* `powerline-active1` & `powerline-active2` _(These are the first and second segments
* `mode-line` _(The normal mode line face in the central segment)_
* `powerline-inactive` & `powerline-inactive2` _(The same but for inactive buffers)_
* `mode-line-inactive` _(The central part of the inactive mode line)_

Unfortunately, very few themes implement the `spaceline-highlight-face` so it doesn't always get defined... There's also the `spaceline-highlight-face-func` which is a variable that you can set in order to return a face to use for the `spaceline-highlight`, mainly used for changing the colour based on `evil-mode`.

I've written some [glue code](https://github.com/domtronn/emacs/blob/master/init/spaceline-colors.el#L150) which updates colours to my liking for my themes if you're interested.

Lastly, the inactive/active stuff is all defined on a segment by segment basis _(see [here](https://github.com/domtronn/spaceline-all-the-icons.el/blob/master/spaceline-all-the-icons-segments.el#L958) for example)_. And I've tried to set a lot of the segments to not show when the buffer is inactive, both to save space and also because I _(personally)_ don't find that information useful...

However, I could add a custom setting to override the active setting if you'd like?
