### ISSUE TITLE
Option to use paradox

### ISSUE THREAD

**Issue by podiki** [domtronn/spaceline-all-the-icons.el#26]
Thanks for this great looking modeline! While it has built-in support when using paradox for handling the package interface, the built-in display of updates and using that to update does not use paradox. Could there be an option for that?

**Comment by domtronn** [comment]
Hey @podiki! 

I think I know what you're saying, since `paradox` is _already_ counting the number of upgradeable packages, why not use that instead of having to set up the advice provided with this package?

And I totally agree, that's a good idea 🙂 

I have a question though, the `paradox--upgradeable-packages-number` is only defined _after_ you've been in a paradox buffer, whereas the setup function does a quick check at start up, is that okay?

Otherwise, the setup function does everything you need to and I don't see a need to couple the behaviour to `paradox` as well.

**Comment by podiki** [comment]
Hi @domtronn. Actually it doesn't matter to me what does the upgrade check, though having an optional timer to periodically check for new packages would be great (for those of us that leave emacs running most of the time). What I thought would be easy and helpful is if when clicking on the number of upgrades if that would open `paradox` instead, either by option or if it is found and if not fallback to normal.

**Comment by domtronn** [comment]
Oh I see! That's much simpler than what I've done haha.. I'll see about the periodic timer, but in the mean time it adds advice so that whenever you refresh the package buffer or load the package buffer, it updates that value.

I'll fix the mouse function for you now though :)

**Comment by podiki** [comment]
Thanks!

Yeah, I'm not sure the best way to show updates without running the package manager. An optional feature for a timer (once an hour/day/week or something) seems easiest to me. I would leave it off by default though, as it may not be for everyone, or even maybe better suited for a package like paradox itself. Still, would be a nice feature here :) Anyway, thanks for the quick update!
