### ISSUE TITLE
This package on windows

### ISSUE THREAD

**Issue by BubblesToTheLimit** [domtronn/spaceline-all-the-icons.el#27]
Does anybody have experience with using this package on windows?

I can display this file just fine, so I do have a unicode-enabled font:
http://ergoemacs.org/emacs/unicode.txt

However i cant see any of the icons this theme provides.

If its not supposed to work on windows anyway this can be closed, but it looks so good so i have to ask.

**Comment by domtronn** [comment]
Hey @BubblesToTheLimit, can you provide a screenshot of what's happening?
Have you installed the fonts required by this package? They can be found [here](https://github.com/domtronn/all-the-icons.el/tree/master/fonts) 🙂 

I'm afraid I don't know how to install fonts programatically on a Windows machine, otherwise you could run `all-the-icons-install-fonts`. You can run this, but it'll prompt you for a location to download the fonts to!

**Comment by BubblesToTheLimit** [comment]
Oh i am an idiot, thanks! :)

**Comment by domtronn** [comment]
Glad you got it working :) _(I assume!)_
