### ISSUE TITLE
modeline overflow in adjacent buffer and underling not consistent

### ISSUE THREAD

**Issue by bricewge** [domtronn/spaceline-all-the-icons.el#40]
I get several glitch with the theme and I don't know where to start looking to fix them. 

With solarized the underline is not on a consistent level:
![screen shot 2017-05-22 at 13 44 07](https://cloud.githubusercontent.com/assets/5525646/26307692/2d1b8398-3ef6-11e7-9fe8-d5311133c08d.png)

The buffers on the right have their modeline which overflow on the right buffer:
![screen shot 2017-05-22 at 13 31 26](https://cloud.githubusercontent.com/assets/5525646/26307693/2eb408f6-3ef6-11e7-8b9b-cf5973599da0.png)

**Comment by domtronn** [comment]
Hi @bricewge sorry for the slow response! I'm not sure why the overflow is happening, what version of Emacs are you using and what OS?

I do add a space character with loads of width to make sure there are no gaps, but I wouldn't imagine this would overflow onto buffers on the right! 😅 

However, the underlining issue is known. The mode line modifies the heights & vertical alignments of strings _(to allow for more room to show information)_ and the icons _(because all the different icon fonts have varied heights/vertical alignments)_ so that they line up nicely. 

But because this modifies the text properties, when adding an underscore to the face, this also adheres to the vertical adjust _(`'display (raise 0.X)` property)_.

You could try using a `box` property on the `mode-line` face, this works quite nicely _(see screenshot)_! 

Apart from around the `wave` and `slant` separators unfortunately, but I'm looking into that... You can use the `arrow` one and that works nicely 🙂 

<img width="1016" alt="screen shot 2017-05-30 at 09 35 40" src="https://cloud.githubusercontent.com/assets/5881414/26574970/5c1110c0-451b-11e7-83e8-b4e96dcf3a79.png">

**Comment by domtronn** [comment]
I've managed to reproduce the overflow issue! It seems to only happen on inactive buffers... And when you focus one of these overflowing buffers, when you force a re-render of the mode line it'll go away!

It seems to be due to [this line](https://github.com/domtronn/spaceline-all-the-icons.el/blob/master/spaceline-all-the-icons-segments.el#L1014) which is supposed to just add padding so you don't get any gaps 🙂 

I'll investigate a solution and get back to you!

**Comment by domtronn** [comment]
Hmm, I just found out that this **only** happens in buffers that **don't** have `linum` _(or some variant of it)_ enabled - Which is why you'll see it happening on the Spacemacs splash screen.

**Comment by jwintz** [comment]
Hi @domtronn, @bricewge,

I have the same issue, and yes, I have `nlinum` package required, but not always triggered. It comes from the great `doom`:   `(doom-themes-nlinum-config)`.

<img width="1676" alt="screen shot 2017-06-22 at 21 28 46" src="https://user-images.githubusercontent.com/3277054/27453446-c5d247f8-5796-11e7-8fea-004524af3e6c.png">

You can see on the upper-right buffer, that the modeline is obfuscated.

As I am always playing with frame splitting, it happens a lot!

**Comment by domtronn** [comment]
@jwintz I think the overflowing part should be fixed by your previous PR #58? Could you please verify this as well? :)

**Comment by bricewge** [comment]
The overflow bug is fixed, thanks!
