### ISSUE TITLE
Git status not working by default

### ISSUE THREAD

**Issue by idoo** [domtronn/spaceline-all-the-icons.el#5]
Debugging returns that git no errors but I can't still see that block http://take.ms/jpXFn

**Comment by domtronn** [comment]
What happens if you call `(git-gutter:statistic)` inside a file with diffs?

**Comment by idoo** [comment]
Added 0 lines, deleted 0 lines

But I have such changes that shows by git gutter+ http://take.ms/VZHni

**Comment by idoo** [comment]
Enable git-gutter-mode solve my pain 👍

**Comment by domtronn** [comment]
Interesting, I guess it's because I've been using `git-gutter-fringe` which is derived from `git-gutter` and therefore requires `git-gutter-mode` to be on 😅 

I'm working on a refactor to make the segment work with _both_ `git-gutter` and `git-gutter+`, so I'd be interested if this works for you? As a plus, `git-gutter+` also tells you `modified` buffers lines as well!

**Comment by idoo** [comment]
@domtronn I updated but it still doesn't works for me :(

also I found interesting case — it doesn't works with `global-git-gutter` but works well wit if I enable this mode for current buffer

**Comment by domtronn** [comment]
I've tested this a few times with a blank install of all variants of `git-gutter`, `git-gutter+`, `git-gutter-fringe` and `git-gutter-fringe+` and it seems to work fine when their relevant modes are enabled... 

It also worked when I use both `global-git-gutter-mode` and `global-git-gutter+-mode`... 

I'm sorry it's not working for you though! Would you mind look printing out these variables inside a file with diffs?

```el
git-gutter+-diffinfos
git-gutter:diffinfos
```

**Comment by idoo** [comment]
I don't have such commands, probably that's why, which version of git-gutter+ do you use?

**Comment by domtronn** [comment]
I've got the same version of `git-gutter-plus`, I'm installing it using a package called [`try`](https://github.com/larstvei/Try) so that it's fresh each time I restart emacs. Yes, you're right `git-gutter+` sets the variables to be buffer local, but when you enable the mode in a buffer _(either through global or hooks)_, it should make sure those variables are defined.

Inside your buffer with diffs, what are the values of the following variables?

```el
git-gutter-mode
git-gutter+-mode
```

**Comment by idoo** [comment]
`git-gutter-mode` was disabled
`git-gutter+-mode` was enabled

**Comment by domtronn** [comment]
No surprises there! That's good at least 😅 

I don't get why you don't have `git-gutter+-diffinfos` defined though... It's there for me and should look something like this

```el
((:type deleted :content "..." :start-line 134 :end-line 134)
 (:type added :content "..." :start-line 207 :end-line 207)
 (:type added :content "..." :start-line 276 :end-line 286))
```

**Comment by idoo** [comment]
Probably it's because I use spacemacs init configuration. Can you test it on it, please?

**Comment by domtronn** [comment]
I installed spacemacs, and the `diffinfos` variable was defined as expected, but I still had to installed `git-gutter+` manually...

But I think I know what the problem is! 🎉 

I fixed it in a refactor this morning, I guess it's not built up to Melpa yet... But there's a predicate on the `git-stats` segment _(see [here](https://github.com/domtronn/spaceline-all-the-icons.el/blob/master/spaceline-all-the-icons-segments.el#L671-L672))_ which requires functions to be defined from `git-gutter`!

Could you have a look to see if that line looks like this in your installation? Otherwise, hopefully the new version should be on Melpa soon :)

```el
(and active
      (fboundp 'git-gutter:statistic)
      (not (equal '(0 . 0) (git-gutter:statistic))))
```

**Comment by idoo** [comment]
I have 
```
  :when (and active
             (fboundp 'git-gutter:statistic)
             (not (equal '(0 . 0) (git-gutter:statistic)))))

```

so, my fingers crossed 🤞

**Comment by idoo** [comment]
@domtronn I've added PR to get latest Melpa version in readme https://github.com/domtronn/spaceline-all-the-icons.el/pull/8

**Comment by idoo** [comment]
and it works now 👍
